#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiveDisplay.Resource", IsApplication=true)]

namespace LiveDisplay
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_preview_lockscreen = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int clockLock = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int contenedorDelMenu = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int contenedorPrincipal = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int notificationIcon = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int notificationSettings = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int preview = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int swEnableAwake = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int txtAjustes = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int txtFechaLock = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int About = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Configuracion = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LockScreen = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_config = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int activarawake = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int activarlockscreen = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int ajusteslockscreen = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_title = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int modoactivo = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int placeholder = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
